const SMART_QUOTES = [
  { text: "Satu-satunya cara untuk melakukan pekerjaan hebat adalah dengan mencintai apa yang Anda lakukan.", ref: "Steve Jobs" },
  { text: "Waktu Anda terbatas, jadi jangan sia-siakan dengan menjalani hidup orang lain.", ref: "Steve Jobs" },
  { text: "Inovasi membedakan antara seorang pemimpin dan pengikut.", ref: "Steve Jobs" },
  { text: "Tetaplah lapar, tetaplah merasa bodoh.", ref: "Steve Jobs" },
  { text: "Pekerjaan Anda akan mengisi sebagian besar hidup Anda, dan satu-satunya cara untuk benar-benar puas adalah melakukan apa yang Anda yakini sebagai pekerjaan hebat.", ref: "Steve Jobs" },
  { text: "Menjadi orang terkaya di pemakaman tidak penting bagi saya. Pergi tidur di malam hari dengan mengatakan kita telah melakukan sesuatu yang luar biasa, itulah yang penting.", ref: "Steve Jobs" },
  { text: "Desain bukan hanya seperti apa tampilannya dan rasanya. Desain adalah bagaimana cara kerjanya.", ref: "Steve Jobs" },
  { text: "Mengingat bahwa Anda akan mati adalah cara terbaik yang saya tahu untuk menghindari jebakan berpikir Anda memiliki sesuatu yang rugi.", ref: "Steve Jobs" },
  { text: "Terkadang ketika Anda berinovasi, Anda membuat kesalahan. Yang terbaik adalah mengakuinya dengan cepat dan melanjutkan peningkatan inovasi Anda yang lain.", ref: "Steve Jobs" },
  { text: "Hal-hal berat dalam hidup tidak harus dilakukan sendirian. Kita bisa membangun tim yang hebat.", ref: "Steve Jobs" },
  { text: "Detail itu penting, itu layak untuk ditunggu.", ref: "Steve Jobs" },
  { text: "Mari kita ciptakan hari esok daripada mengkhawatirkan apa yang terjadi kemarin.", ref: "Steve Jobs" },
  { text: "Saya yakin bahwa sekitar setengah dari apa yang membedakan pengusaha sukses dari yang tidak sukses adalah ketekunan murni.", ref: "Steve Jobs" },
  { text: "Teknologi bukan apa-apa. Yang penting adalah Anda memiliki keyakinan pada orang lain, bahwa mereka pada dasarnya baik dan cerdas.", ref: "Steve Jobs" },
  { text: "Kreativitas hanyalah menghubungkan berbagai hal.", ref: "Steve Jobs" },
  { text: "Fokus berarti mengatakan tidak pada ratusan ide bagus lainnya.", ref: "Steve Jobs" },
  { text: "Sederhana bisa lebih sulit daripada rumit: Anda harus bekerja keras untuk menjernihkan pikiran agar bisa membuatnya sederhana.", ref: "Steve Jobs" },
  { text: "Orang-orang yang cukup gila untuk berpikir mereka bisa mengubah dunia adalah orang-orang yang benar-benar melakukannya.", ref: "Steve Jobs" },
  { text: "Jalanilah setiap hari seolah-olah itu adalah hari terakhir Anda, dan suatu hari Anda pasti akan benar.", ref: "Steve Jobs" },
  { text: "Intuisi Anda tahu apa yang benar-benar ingin Anda capai.", ref: "Steve Jobs" },
  { text: "Kebanggaan akan pekerjaan Anda adalah kunci dari kesuksesan jangka panjang.", ref: "Steve Jobs" },
  { text: "Kualitas lebih penting daripada kuantitas. Satu home run jauh lebih baik daripada dua double.", ref: "Steve Jobs" },
  { text: "Terkadang hidup memukul kepala Anda dengan batu bata. Jangan kehilangan keyakinan.", ref: "Steve Jobs" },
  { text: "Perjalanan itu sendiri adalah upahnya.", ref: "Steve Jobs" },
  { text: "Sangat menyenangkan untuk melakukan hal-hal yang tidak mungkin.", ref: "Steve Jobs" },
  { text: "Imajinasi lebih penting daripada pengetahuan. Pengetahuan terbatas, sedangkan imajinasi mencakup seluruh dunia.", ref: "Albert Einstein" },
  { text: "Di tengah kesulitan terdapat kesempatan.", ref: "Albert Einstein" },
  { text: "Seseorang yang tidak pernah membuat kesalahan tidak pernah mencoba sesuatu yang baru.", ref: "Albert Einstein" },
  { text: "Cobalah untuk tidak menjadi orang yang sukses, tetapi cobalah menjadi orang yang bernilai.", ref: "Albert Einstein" },
  { text: "Ada dua cara untuk menjalani hidup Anda. Salah satunya adalah dengan berpikir seolah-olah tidak ada mukjizat. Yang lainnya adalah berpikir seolah-olah segala sesuatu adalah mukjizat.", ref: "Albert Einstein" },
  { text: "Satu-satunya sumber pengetahuan adalah pengalaman.", ref: "Albert Einstein" },
  { text: "Logika akan membawa Anda dari A ke B. Imajinasi akan membawa Anda ke mana saja.", ref: "Albert Einstein" },
  { text: "Kegilaan adalah melakukan hal yang sama berulang-ulang dan mengharapkan hasil yang berbeda.", ref: "Albert Einstein" },
  { text: "Belajar dari kemarin, hidup untuk hari ini, berharap untuk besok. Yang penting adalah tidak berhenti bertanya.", ref: "Albert Einstein" },
  { text: "Kelemahan sikap menjadi kelemahan karakter.", ref: "Albert Einstein" },
  { text: "Hidup ini seperti mengendarai sepeda. Untuk menjaga keseimbangan, Anda harus terus bergerak.", ref: "Albert Einstein" },
  { text: "Perdamaian tidak dapat dijaga dengan kekerasan; itu hanya dapat dicapai dengan pemahaman.", ref: "Albert Einstein" },
  { text: "Seni tertinggi guru adalah membangun kegembiraan dalam ekspresi kreatif dan pengetahuan.", ref: "Albert Einstein" },
  { text: "Siapa pun yang tidak menganggap serius kebenaran dalam hal-hal kecil tidak dapat dipercaya dalam hal-hal besar.", ref: "Albert Einstein" },
  { text: "Pertanyaan penting untuk masa depan Anda adalah apa yang Anda lakukan hari ini.", ref: "Albert Einstein" },
  { text: "Ukuran kecerdasan adalah kemampuan untuk berubah.", ref: "Albert Einstein" },
  { text: "Hanya kehidupan yang dijalani untuk orang lain yang merupakan kehidupan yang berharga.", ref: "Albert Einstein" },
  { text: "Segalanya harus dibuat sesederhana mungkin, tetapi tidak lebih sederhana.", ref: "Albert Einstein" },
  { text: "Kemarahan hanya bersemayam di dalam dada orang bodoh.", ref: "Albert Einstein" },
  { text: "Informasi bukanlah pengetahuan.", ref: "Albert Einstein" },
  { text: "Genius adalah 1% bakat dan 99% kerja keras.", ref: "Albert Einstein" },
  { text: "Nilai seorang manusia harus dilihat dari apa yang dia berikan dan bukan dari apa yang dia mampu terima.", ref: "Albert Einstein" },
  { text: "Waktu adalah ilusi.", ref: "Albert Einstein" },
  { text: "Keadaan yang paling indah yang dapat kita alami adalah misteri.", ref: "Albert Einstein" },
  { text: "Sains tanpa agama adalah lumpuh, agama tanpa sains adalah buta.", ref: "Albert Einstein" },
  { text: "Jadilah perubahan yang ingin Anda lihat di dunia.", ref: "Mahatma Gandhi" },
  { text: "Hiduplah seolah-olah Anda akan mati besok. Belajarlah seolah-olah Anda akan hidup selamanya.", ref: "Mahatma Gandhi" },
  { text: "Kekuatan tidak datang dari kapasitas fisik. Itu datang dari kemauan yang tidak tergoyahkan.", ref: "Mahatma Gandhi" },
  { text: "Kebahagiaan adalah ketika apa yang Anda pikirkan, apa yang Anda katakan, dan apa yang Anda lakukan berada dalam keharmonisan.", ref: "Mahatma Gandhi" },
  { text: "Orang yang lemah tidak pernah bisa memaafkan. Pengampunan adalah atribut dari orang yang kuat.", ref: "Mahatma Gandhi" },
  { text: "Masa depan bergantung pada apa yang Anda lakukan hari ini.", ref: "Mahatma Gandhi" },
  { text: "Cara terbaik untuk menemukan diri Anda adalah kehilangan diri Anda dalam pelayanan kepada orang lain.", ref: "Mahatma Gandhi" },
  { text: "Kasih sayang adalah kekuatan terbesar yang dimiliki umat manusia.", ref: "Mahatma Gandhi" },
  { text: "Keyakinan bukanlah sesuatu untuk digenggam, melainkan sesuatu untuk dijalani.", ref: "Mahatma Gandhi" },
  { text: "Sedikit tindakan lebih berharga daripada berton-ton khotbah.", ref: "Mahatma Gandhi" },
  { text: "Kemarahan dan intoleransi adalah musuh dari pemahaman yang benar.", ref: "Mahatma Gandhi" },
  { text: "Kemenangan yang diperoleh dengan kekerasan sama saja dengan kekalahan, karena itu hanya sementara.", ref: "Mahatma Gandhi" },
  { text: "Kebebasan tidak ada gunanya jika tidak mencakup kebebasan untuk melakukan kesalahan.", ref: "Mahatma Gandhi" },
  { text: "Mata ganti mata hanya akan membuat seluruh dunia buta.", ref: "Mahatma Gandhi" },
  { text: "Bumi menyediakan cukup untuk memenuhi kebutuhan setiap orang, tetapi tidak untuk keserakahan setiap orang.", ref: "Mahatma Gandhi" },
  { text: "Hubungan interpersonal didasarkan pada rasa saling menghormati dan kejujuran.", ref: "Mahatma Gandhi" },
  { text: "Pertama mereka mengabaikan Anda, kemudian mereka menertawakan Anda, kemudian mereka melawan Anda, lalu Anda menang.", ref: "Mahatma Gandhi" },
  { text: "Kejujuran adalah langkah awal menuju integritas diri.", ref: "Mahatma Gandhi" },
  { text: "Nilai dari sebuah tindakan terletak pada penyelesaiannya sampai akhir.", ref: "Mahatma Gandhi" },
  { text: "Jangan biarkan matahari terbenam dengan kemarahan di dalam hati Anda.", ref: "Mahatma Gandhi" },
  { text: "Kekuatan sejati terletak pada kedamaian pikiran.", ref: "Mahatma Gandhi" },
  { text: "Doa adalah kunci di pagi hari dan sekrup pengunci di malam hari.", ref: "Mahatma Gandhi" },
  { text: "Kerapian dan kesederhanaan adalah mahkota dari jiwa yang mulia.", ref: "Mahatma Gandhi" },
  { text: "Tidak ada yang bisa menyakiti saya tanpa izin saya.", ref: "Mahatma Gandhi" },
  { text: "Kemuliaan terletak pada upaya untuk mencapai tujuan, bukan pada pencapaiannya saja.", ref: "Mahatma Gandhi" },
  { text: "Sukses bukanlah akhir, kegagalan bukanlah fatal: keberanian untuk melanjutkanlah yang penting.", ref: "Winston Churchill" },
  { text: "Seorang pesimis melihat kesulitan di setiap kesempatan; seorang optimis melihat kesempatan di setiap kesulitan.", ref: "Winston Churchill" },
  { text: "Kita hidup dari apa yang kita dapatkan, tetapi kita membuat kehidupan dari apa yang kita berikan.", ref: "Winston Churchill" },
  { text: "Sikap adalah hal kecil yang membuat perbedaan besar.", ref: "Winston Churchill" },
  { text: "Jika Anda sedang berjalan melewati neraka, teruslah berjalan.", ref: "Winston Churchill" },
  { text: "Meningkatkan berarti berubah; menjadi sempurna berarti sering berubah.", ref: "Winston Churchill" },
  { text: "Keberanian adalah apa yang diperlukan untuk berdiri dan berbicara; keberanian juga apa yang diperlukan untuk duduk dan mendengarkan.", ref: "Winston Churchill" },
  { text: "Sejarah akan ramah kepada saya karena saya bermaksud menulisnya.", ref: "Winston Churchill" },
  { text: "Kesulitan yang dihadapi dengan berani adalah kemenangan setengah jalan.", ref: "Winston Churchill" },
  { text: "Jangan pernah menyerah, jangan pernah menyerah, jangan pernah, jangan pernah, jangan pernah.", ref: "Winston Churchill" },
  { text: "Harga dari keagungan adalah tanggung jawab.", ref: "Winston Churchill" },
  { text: "Secara pribadi saya selalu siap untuk belajar, meskipun saya tidak selalu suka diajar.", ref: "Winston Churchill" },
  { text: "Kita adalah tuan atas kata-kata yang tidak terucapkan, tetapi budak dari kata-kata yang kita biarkan lolos.", ref: "Winston Churchill" },
  { text: "Keraguan hanya bisa disembuhkan dengan tindakan nyata.", ref: "Winston Churchill" },
  { text: "Semua hal besar itu sederhana, dan banyak yang dapat diungkapkan dalam satu kata: kebebasan, keadilan, kehormatan, tugas, belas kasih, harapan.", ref: "Winston Churchill" },
  { text: "Ketika Anda tidak memiliki musuh di dalam, musuh di luar tidak dapat menyakiti Anda.", ref: "Winston Churchill" },
  { text: "Masa depan adalah milik mereka yang mempersiapkannya hari ini.", ref: "Winston Churchill" },
  { text: "Ujian terbesar dari karakter adalah bagaimana kita menangani kegagalan.", ref: "Winston Churchill" },
  { text: "Satu-satunya batasan untuk pencapaian kita hari esok adalah keraguan kita hari ini.", ref: "Winston Churchill" },
  { text: "Konsistensi adalah fondasi dari reputasi yang kokoh.", ref: "Winston Churchill" },
  { text: "Tugas kita adalah melakukan apa yang benar, bukan apa yang mudah.", ref: "Winston Churchill" },
  { text: "Kekuatan sejati lahir dari perjuangan yang tak kenal lelah.", ref: "Winston Churchill" },
  { text: "Jangan biarkan ketakutan menghalangi Anda melakukan apa yang Anda tahu benar.", ref: "Winston Churchill" },
  { text: "Peluang tidak datang dengan sendirinya, Anda yang menciptakannya.", ref: "Winston Churchill" },
  { text: "Optimisme adalah kunci untuk melewati masa-masa tersulit.", ref: "Winston Churchill" },
  { text: "Anda memiliki kendali atas pikiran Anda - bukan peristiwa di luar. Sadarilah ini, dan Anda akan menemukan kekuatan.", ref: "Marcus Aurelius" },
  { text: "Kebahagiaan hidup Anda bergantung pada kualitas pikiran Anda.", ref: "Marcus Aurelius" },
  { text: "Kematian tersenyum pada kita semua, yang bisa dilakukan manusia adalah tersenyum kembali.", ref: "Marcus Aurelius" },
  { text: "Lakukan setiap tindakan dalam hidup seolah-olah itu adalah tindakan terakhir Anda.", ref: "Marcus Aurelius" },
  { text: "Balas dendam terbaik adalah dengan tidak menjadi seperti musuhmu.", ref: "Marcus Aurelius" },
  { text: "Kerugian tidak lain adalah perubahan, dan perubahan adalah kesenangan alam.", ref: "Marcus Aurelius" },
  { text: "Masa depan tidak boleh mengkhawatirkanmu. Kamu akan menghadapinya dengan senjata akal yang sama yang mempersenjataimu melawan masa kini.", ref: "Marcus Aurelius" },
  { text: "Jiwa diwarnai dengan warna pikiran-pikirannya.", ref: "Marcus Aurelius" },
  { text: "Sangat sedikit yang dibutuhkan untuk membuat hidup bahagia; itu semua ada di dalam dirimu sendiri, dalam cara berpikirmu.", ref: "Marcus Aurelius" },
  { text: "Kapan pun kamu ingin menghibur diri, pikirkanlah kualitas-kualitas baik dari orang-orang di sekitarmu.", ref: "Marcus Aurelius" },
  { text: "Terimalah hal-hal yang ditakdirkan untukmu, dan cintailah orang-orang yang bersamamu, tetapi lakukanlah dengan segenap hatimu.", ref: "Marcus Aurelius" },
  { text: "Pekerjaan terbaik yang bisa kamu lakukan adalah memperbaiki dirimu sendiri.", ref: "Marcus Aurelius" },
  { text: "Jangan habiskan waktu lagi untuk berdebat tentang apa seharusnya pria yang baik itu. Jadilah pria yang baik.", ref: "Marcus Aurelius" },
  { text: "Segala sesuatu yang kita dengar adalah pendapat, bukan fakta. Segala sesuatu yang kita lihat adalah perspektif, bukan kebenaran.", ref: "Marcus Aurelius" },
  { text: "Ingatlah seberapa lama kamu telah menunda hal-hal ini.", ref: "Marcus Aurelius" },
  { text: "Kehidupan seseorang adalah apa yang dibuat oleh pikiran mereka.", ref: "Marcus Aurelius" },
  { text: "Setiap orang hidup di masa kini saja, yang merupakan momen singkat.", ref: "Marcus Aurelius" },
  { text: "Mulailah setiap hari dengan berkata pada diri sendiri: Hari ini saya akan bertemu dengan orang yang suka mencampuri urusan orang lain, tidak berterima kasih, sombong, tidak jujur, cemburu, dan tidak ramah.", ref: "Marcus Aurelius" },
  { text: "Sifat manusia membutuhkan kerja sama, bukan perpecahan.", ref: "Marcus Aurelius" },
  { text: "Jika itu tidak benar, jangan katakan; jika itu tidak benar, jangan lakukan.", ref: "Marcus Aurelius" },
  { text: "Akal budi adalah pemandu terbaik bagi jiwa.", ref: "Marcus Aurelius" },
  { text: "Ketahanan adalah kekuatan untuk menanggung apa yang tidak bisa diubah.", ref: "Marcus Aurelius" },
  { text: "Nilai seseorang diukur dari nilai hal-hal yang dia hargai.", ref: "Marcus Aurelius" },
  { text: "Jangan bertindak seolah-olah kamu memiliki sepuluh ribu tahun untuk hidup. Takdir bergantung padamu selagi kamu hidup.", ref: "Marcus Aurelius" },
  { text: "Waktu adalah sejenis sungai peristiwa, dan arusnya deras.", ref: "Marcus Aurelius" },
  { text: "Bukan karena hal-hal itu sulit kita tidak berani; melainkan karena kita tidak berani hal-hal itu menjadi sulit.", ref: "Seneca" },
  { text: "Kekayaan terbesar adalah kepuasan dengan apa yang kita miliki.", ref: "Seneca" },
  { text: "Keberuntungan adalah apa yang terjadi ketika persiapan bertemu dengan kesempatan.", ref: "Seneca" },
  { text: "Kita lebih sering menderita dalam imajinasi kita daripada dalam kenyataan.", ref: "Seneca" },
  { text: "Selagi kita menunda, hidup terus berjalan.", ref: "Seneca" },
  { text: "Bergaullah dengan orang-orang yang kemungkinan besar akan membuat Anda menjadi lebih baik.", ref: "Seneca" },
  { text: "Satu-satunya obat untuk kemarahan adalah penundaan.", ref: "Seneca" },
  { text: "Tidak ada orang yang bisa hidup bahagia jika dia hanya memperhatikan dirinya sendiri.", ref: "Seneca" },
  { text: "Hidup itu panjang jika Anda tahu cara menggunakannya.", ref: "Seneca" },
  { text: "Bukan orang yang memiliki sedikit yang miskin, tetapi orang yang mendambakan lebih banyak.", ref: "Seneca" },
  { text: "Kesulitan memperkuat pikiran, seperti halnya kerja fisik memperkuat tubuh.", ref: "Seneca" },
  { text: "Di mana ada manusia, di situ ada kesempatan untuk berbuat baik.", ref: "Seneca" },
  { text: "Sebagian dari kesembuhan adalah keinginan untuk disembuhkan.", ref: "Seneca" },
  { text: "Jika Anda ingin dicintai, cintailah.", ref: "Seneca" },
  { text: "Hidup adalah badai yang terus-menerus menguji jangkar kita.", ref: "Seneca" },
  { text: "Akal sehat adalah pertahanan terbaik melawan nasib buruk.", ref: "Seneca" },
  { text: "Mengabaikan rasa sakit adalah langkah pertama menuju kedamaian.", ref: "Seneca" },
  { text: "Pendidikan terbaik adalah yang mengajarkan kita bagaimana cara hidup, bukan hanya bagaimana cara mencari nafkah.", ref: "Seneca" },
  { text: "Setiap hari adalah kehidupan baru bagi orang yang bijaksana.", ref: "Seneca" },
  { text: "Kematian adalah pembebasan dari segala rasa sakit.", ref: "Seneca" },
  { text: "Tidak ada pelayaran yang aman bagi kapal yang tidak tahu ke pelabuhan mana ia menuju.", ref: "Seneca" },
  { text: "Waktu mengungkapkan kebenaran.", ref: "Seneca" },
  { text: "Belajarlah untuk merasa puas dengan kemajuan kecil Anda.", ref: "Seneca" },
  { text: "Kebajikan adalah upahnya sendiri.", ref: "Seneca" },
  { text: "Jangan biarkan pikiran Anda terbebani oleh kekhawatiran masa depan.", ref: "Seneca" },
  { text: "Satu-satunya hal yang saya tahu adalah bahwa saya tidak tahu apa-apa.", ref: "Socrates" },
  { text: "Hidup yang tidak diuji tidak layak untuk dijalani.", ref: "Socrates" },
  { text: "Cara termudah dan termulia adalah tidak menekan orang lain, melainkan memperbaiki diri sendiri.", ref: "Socrates" },
  { text: "Pikiran yang kuat mendiskusikan ide, pikiran rata-rata mendiskusikan peristiwa, pikiran lemah mendiskusikan orang.", ref: "Socrates" },
  { text: "Pendidikan adalah menyalakan api, bukan mengisi wadah.", ref: "Socrates" },
  { text: "Jadilah seperti yang Anda inginkan.", ref: "Socrates" },
  { text: "Kunci kebahagiaan bukanlah mencari lebih banyak, tetapi mengembangkan kapasitas untuk menikmati lebih sedikit.", ref: "Socrates" },
  { text: "Ingatlah bahwa tidak ada kondisi manusia yang permanen; dengan demikian Anda tidak akan terlalu gembira dalam keberuntungan atau terlalu sedih dalam kemalangan.", ref: "Socrates" },
  { text: "Kematian mungkin merupakan berkat terbesar bagi manusia.", ref: "Socrates" },
  { text: "Dari keinginan terdalam sering kali lahir kebencian yang paling mematikan.", ref: "Socrates" },
  { text: "Kita adalah apa yang kita lakukan berulang kali. Keunggulan, bukanlah suatu tindakan, melainkan kebiasaan.", ref: "Aristotle" },
  { text: "Mengenal diri sendiri adalah awal dari semua kebijaksanaan.", ref: "Aristotle" },
  { text: "Harapan adalah mimpi yang terjaga.", ref: "Aristotle" },
  { text: "Kebahagiaan adalah makna dan tujuan hidup, seluruh arah dan akhir dari eksistensi manusia.", ref: "Aristotle" },
  { text: "Akar dari pendidikan itu pahit, tetapi buahnya manis.", ref: "Aristotle" },
  { text: "Pikiran yang terdidik ditandai dengan kemampuan untuk menjamu suatu pemikiran tanpa menerimanya.", ref: "Aristotle" },
  { text: "Menyukai pekerjaan Anda memberikan kesempurnaan pada hasil kerja.", ref: "Aristotle" },
  { text: "Teman sejati adalah satu jiwa yang tinggal di dua tubuh.", ref: "Aristotle" },
  { text: "Tujuan seni bukanlah mewakili penampilan luar dari berbagai hal, tetapi signifikansi batiniahnya.", ref: "Aristotle" },
  { text: "Keberanian adalah kualitas manusia yang pertama karena kualitas itulah yang menjamin kualitas lainnya.", ref: "Aristotle" },
  { text: "Kemenangan terbesar kita bukanlah tidak pernah jatuh, tetapi bangkit setiap kali kita jatuh.", ref: "Confucius" },
  { text: "Hidup itu sangat sederhana, tetapi kita bersikeras membuatnya rumit.", ref: "Confucius" },
  { text: "Ke mana pun Anda pergi, pergilah dengan segenap hati Anda.", ref: "Confucius" },
  { text: "Pilihlah pekerjaan yang Anda sukai, dan Anda tidak perlu bekerja sehari pun dalam hidup Anda.", ref: "Confucius" },
  { text: "Kemauan untuk menang, keinginan untuk sukses, desakan untuk mencapai potensi penuh Anda... ini adalah kunci yang akan membuka pintu menuju keunggulan pribadi.", ref: "Confucius" },
  { text: "Melihat apa yang benar dan tidak melakukannya adalah kurangnya keberanian.", ref: "Confucius" },
  { text: "Orang yang memindahkan gunung mulai dengan membawa batu-batu kecil.", ref: "Confucius" },
  { text: "Hormati diri Anda sendiri dan orang lain akan menghormati Anda.", ref: "Confucius" },
  { text: "Keheningan adalah teman sejati yang tidak pernah mengkhianati.", ref: "Confucius" },
  { text: "Belajar tanpa berpikir adalah sia-sia; berpikir tanpa belajar adalah berbahaya.", ref: "Confucius" },
  { text: "Perjalanan seribu mil dimulai dengan satu langkah.", ref: "Lao Tzu" },
  { text: "Ketika saya melepaskan diri saya yang sekarang, saya menjadi seperti apa saya nantinya.", ref: "Lao Tzu" },
  { text: "Menguasai orang lain adalah kekuatan. Menguasai diri sendiri adalah kekuatan sejati.", ref: "Lao Tzu" },
  { text: "Seorang musafir yang baik tidak memiliki rencana tetap dan tidak berniat tiba.", ref: "Lao Tzu" },
  { text: "Kebaikan dalam kata-kata menciptakan keyakinan. Kebaikan dalam berpikir menciptakan kebiasaan. Kebaikan dalam memberi menciptakan kasih.", ref: "Lao Tzu" },
  { text: "Jika Anda depresi, Anda hidup di masa lalu. Jika Anda cemas, Anda hidup di masa depan. Jika Anda damai, Anda hidup di masa kini.", ref: "Lao Tzu" },
  { text: "Kesehatan adalah kepemilikan terbesar. Kepuasan adalah harta terbesar. Keyakinan adalah teman terbesar.", ref: "Lao Tzu" },
  { text: "Air adalah hal yang paling lembut, namun dapat menembus hal yang paling keras.", ref: "Lao Tzu" },
  { text: "Tindakan tanpa pamrih membawa kedamaian abadi.", ref: "Lao Tzu" },
  { text: "Kesederhanaan, kesabaran, kasih sayang. Tiga hal ini adalah harta terbesar Anda.", ref: "Lao Tzu" },
  { text: "Tampaknya selalu mustahil sampai itu selesai.", ref: "Nelson Mandela" },
  { text: "Pendidikan adalah senjata paling ampuh yang dapat Anda gunakan untuk mengubah dunia.", ref: "Nelson Mandela" },
  { text: "Saya tidak pernah kalah. Saya menang atau belajar.", ref: "Nelson Mandela" },
  { text: "Keberanian bukanlah ketiadaan rasa takut, melainkan kemenangan atas rasa takut.", ref: "Nelson Mandela" },
  { text: "Menjadi bebas bukan hanya membuang rantai seseorang, melainkan hidup dengan cara yang menghormati dan meningkatkan kebebasan orang lain.", ref: "Nelson Mandela" },
  { text: "Kesulitan mematahkan beberapa orang tetapi membuat orang lain kuat.", ref: "Nelson Mandela" },
  { text: "Kepala yang baik dan hati yang baik selalu merupakan kombinasi yang hebat.", ref: "Nelson Mandela" },
  { text: "Jangan menilai saya dari kesuksesan saya, nilailah saya dari seberapa sering saya jatuh dan bangkit kembali.", ref: "Nelson Mandela" },
  { text: "Kebencian itu seperti meminum racun dan berharap musuh Anda mati.", ref: "Nelson Mandela" },
  { text: "Saat kita membiarkan cahaya kita bersinar, kita secara tidak sadar memberi orang lain izin untuk melakukan hal yang sama.", ref: "Nelson Mandela" },
  { text: "Pada akhirnya, bukan tahun-tahun dalam hidup Anda yang diperhitungkan. Melainkan kehidupan dalam tahun-tahun Anda.", ref: "Abraham Lincoln" },
  { text: "Cara terbaik untuk memprediksi masa depan Anda adalah dengan menciptakannya.", ref: "Abraham Lincoln" },
  { text: "Apapun dirimu, jadilah yang terbaik.", ref: "Abraham Lincoln" },
  { text: "Saya berjalan lambat, tetapi saya tidak pernah berjalan mundur.", ref: "Abraham Lincoln" },
  { text: "Hampir semua orang dapat menanggung kemalangan, tetapi jika Anda ingin menguji karakter seseorang, berilah dia kekuasaan.", ref: "Abraham Lincoln" },
  { text: "Saya sukses hari ini karena saya memiliki teman yang mempercayai saya dan saya tidak tega mengecewakannya.", ref: "Abraham Lincoln" },
  { text: "Pastikan Anda meletakkan kaki Anda di tempat yang tepat, lalu berdiri kokoh.", ref: "Abraham Lincoln" },
  { text: "Karakter itu seperti pohon dan reputasi seperti bayangannya. Bayangan adalah apa yang kita pikirkan tentangnya; pohon adalah hal yang nyata.", ref: "Abraham Lincoln" },
  { text: "Saya tidak terlalu memikirkan pria yang tidak lebih bijaksana hari ini daripada kemarin.", ref: "Abraham Lincoln" },
  { text: "Ketika saya berbuat baik, saya merasa baik. Ketika saya berbuat jahat, saya merasa jahat. Itulah agama saya.", ref: "Abraham Lincoln" },
  { text: "Semua impian kita dapat menjadi kenyataan jika kita memiliki keberanian untuk mengejarnya.", ref: "Walt Disney" },
  { text: "Cara untuk memulai adalah berhenti berbicara dan mulai melakukan.", ref: "Walt Disney" },
  { text: "Jika Anda bisa memimpikannya, Anda bisa melakukannya.", ref: "Walt Disney" },
  { text: "Tawa itu abadi, imajinasi tidak memiliki usia, dan mimpi selamanya.", ref: "Walt Disney" },
  { text: "Lakukan pekerjaan Anda dengan sangat baik sehingga mereka ingin melihatnya lagi dan membawa teman-teman mereka.", ref: "Walt Disney" },
  { text: "Semakin Anda menyukai diri Anda sendiri, semakin sedikit Anda seperti orang lain, yang membuat Anda unik.", ref: "Walt Disney" },
  { text: "Kekhawatiran itu sia-sia dan tidak menyelesaikan masalah apa pun.", ref: "Walt Disney" },
  { text: "Waktu dan arus tidak menunggu siapa pun, mulailah langkah Anda sekarang.", ref: "Walt Disney" },
  { text: "Keberanian adalah kunci dari setiap petualangan besar.", ref: "Walt Disney" },
  { text: "Ada lebih banyak harta karun di dalam buku daripada di semua jarahan bajak laut di Pulau Harta Karun.", ref: "Walt Disney" },
  { text: "Hal-hal terbaik dan terindah di dunia tidak dapat dilihat atau disentuh, melainkan harus dirasakan dengan hati.", ref: "Helen Keller" },
  { text: "Optimisme adalah keyakinan yang mengarah pada pencapaian. Tidak ada yang bisa dilakukan tanpa harapan dan keyakinan.", ref: "Helen Keller" },
  { text: "Sendiri kita bisa berbuat sedikit; bersama-sama kita bisa berbuat banyak.", ref: "Helen Keller" },
  { text: "Menjaga wajah kita tetap menghadap sinar matahari membuat kita tidak bisa melihat bayangan.", ref: "Helen Keller" },
  { text: "Hidup adalah petualangan yang berani atau tidak sama sekali.", ref: "Helen Keller" },
  { text: "Karakter tidak dapat dikembangkan dengan mudah dan tenang. Hanya melalui pengalaman ujian dan penderitaan jiwa dapat diperkuat.", ref: "Helen Keller" },
  { text: "Tidak ada orang pesimis yang pernah menemukan rahasia bintang, atau berlayar ke daratan baru.", ref: "Helen Keller" },
  { text: "Kita tidak pernah bisa belajar untuk bersabar jika hanya ada kegembiraan di dunia.", ref: "Helen Keller" },
  { text: "Meskipun dunia ini penuh dengan penderitaan, dunia ini juga penuh dengan cara mengatasinya.", ref: "Helen Keller" },
  { text: "Pendidikan harus membimbing kita menuju kebebasan berpikir.", ref: "Helen Keller" },
  { text: "Saya belum gagal. Saya baru saja menemukan 10.000 cara yang tidak berhasil.", ref: "Thomas Edison" },
  { text: "Banyak kegagalan hidup dialami oleh orang-orang yang tidak menyadari seberapa dekat mereka dengan kesuksesan ketika mereka menyerah.", ref: "Thomas Edison" },
  { text: "Jenius adalah satu persen inspirasi, sembilan puluh sembilan persen keringat.", ref: "Thomas Edison" },
  { text: "Nilai dari sebuah ide terletak pada penggunaannya.", ref: "Thomas Edison" },
  { text: "Ada cara untuk melakukannya dengan lebih baik - temukanlah.", ref: "Thomas Edison" },
  { text: "Kesibukan tidak selalu berarti pekerjaan nyata. Tujuan dari semua pekerjaan adalah produksi atau pencapaian.", ref: "Thomas Edison" },
  { text: "Hanya karena sesuatu tidak berjalan seperti yang Anda rencanakan, tidak berarti itu tidak berguna.", ref: "Thomas Edison" },
  { text: "Tiga hal penting untuk mencapai sesuatu yang berharga adalah: kerja keras, ketekunan, dan akal sehat.", ref: "Thomas Edison" },
  { text: "Kelemahan terbesar kita terletak pada menyerah. Cara paling pasti untuk sukses adalah selalu mencoba sekali lagi.", ref: "Thomas Edison" },
  { text: "Saya tahu apa yang harus saya lakukan, dan saya mulai mengerjakannya.", ref: "Thomas Edison" },
  { text: "Apakah Anda pikir Anda bisa, atau Anda pikir Anda tidak bisa - Anda benar.", ref: "Henry Ford" },
  { text: "Kegagalan hanyalah kesempatan untuk memulai lagi, kali ini dengan lebih cerdas.", ref: "Henry Ford" },
  { text: "Berkumpul bersama adalah awal; menjaga kebersamaan adalah kemajuan; bekerja sama adalah kesuksesan.", ref: "Henry Ford" },
  { text: "Siapa pun yang berhenti belajar adalah orang tua, baik pada usia dua puluh atau delapan puluh tahun.", ref: "Henry Ford" },
  { text: "Hambatan adalah hal-hal menakutkan yang Anda lihat ketika Anda mengalihkan pandangan dari tujuan Anda.", ref: "Henry Ford" },
  { text: "Jangan mencari kesalahan, carilah jalan keluar.", ref: "Henry Ford" },
  { text: "Kualitas berarti melakukan hal yang benar ketika tidak ada orang yang melihat.", ref: "Henry Ford" },
  { text: "Berpikir adalah pekerjaan terberat yang ada, yang mungkin merupakan alasan mengapa sedikit sekali orang yang terlibat di dalamnya.", ref: "Henry Ford" },
  { text: "Sebagian besar orang menghabiskan lebih banyak waktu dan energi untuk memutar-mutar masalah daripada mencoba menyelesaikannya.", ref: "Henry Ford" },
  { text: "Jika ada rahasia sukses, itu terletak pada kemampuan untuk melihat dari sudut pandang orang lain.", ref: "Henry Ford" },
  { text: "Jangan pergi ke mana jalan menuntun, pergilah ke tempat yang tidak ada jalan dan tinggalkan jejak.", ref: "Ralph Waldo Emerson" },
  { text: "Menjadi diri sendiri di dunia yang terus berusaha membuat Anda menjadi sesuatu yang lain adalah pencapaian terbesar.", ref: "Ralph Waldo Emerson" },
  { text: "Satu-satunya cara untuk memiliki teman adalah menjadi teman.", ref: "Ralph Waldo Emerson" },
  { text: "Kekuatan terbesar kita tidak terletak pada tidak pernah jatuh, melainkan bangkit setelah jatuh.", ref: "Ralph Waldo Emerson" },
  { text: "Setiap menit Anda marah, Anda kehilangan enam puluh detik kedamaian pikiran.", ref: "Ralph Waldo Emerson" },
  { text: "Tanpa antusiasme, tidak ada hal besar yang pernah dicapai.", ref: "Ralph Waldo Emerson" },
  { text: "Takut adalah hambatan terbesar menuju kebebasan berpikir.", ref: "Ralph Waldo Emerson" },
  { text: "Apa yang terletak di belakang kita dan apa yang terletak di depan kita adalah hal-hal kecil dibandingkan dengan apa yang ada di dalam kita.", ref: "Ralph Waldo Emerson" },
  { text: "Kedamaian tidak dapat dicapai di luar diri Anda.", ref: "Ralph Waldo Emerson" },
  { text: "Adopsi kecepatan alam: rahasianya adalah kesabaran.", ref: "Ralph Waldo Emerson" },
  { text: "Dua hari terpenting dalam hidup Anda adalah hari Anda dilahirkan dan hari Anda menemukan alasannya.", ref: "Mark Twain" },
  { text: "Rahasia untuk maju adalah memulai.", ref: "Mark Twain" },
  { text: "Kebaikan adalah bahasa yang didengar orang tuli dan dilihat orang buta.", ref: "Mark Twain" },
  { text: "Setiap kali Anda menemukan diri Anda berada di pihak mayoritas, inilah saatnya untuk berhenti dan merenung.", ref: "Mark Twain" },
  { text: "Jangan biarkan sekolah mengganggu pendidikan Anda.", ref: "Mark Twain" },
  { text: "Tindakan berbicara lebih keras daripada kata-kata, tetapi tidak sesering itu.", ref: "Mark Twain" },
  { text: "Keberanian adalah perlawanan terhadap ketakutan, penguasaan atas ketakutan - bukan ketiadaan ketakutan.", ref: "Mark Twain" },
  { text: "Jauhilah orang-orang yang mencoba meremehkan ambisi Anda. Orang kecil selalu melakukan itu.", ref: "Mark Twain" },
  { text: "Pekerjaan terdiri dari apa pun yang wajib dilakukan oleh seseorang. Bermain terdiri dari apa pun yang tidak wajib dilakukan oleh seseorang.", ref: "Mark Twain" },
  { text: "Kebenaran lebih aneh daripada fiksi.", ref: "Mark Twain" },
  { text: "Anda tidak dapat mengontrol semua peristiwa yang terjadi pada Anda, tetapi Anda dapat memutuskan untuk tidak dikurangi olehnya.", ref: "Maya Angelou" },
  { text: "Orang-orang akan melupakan apa yang Anda katakan, orang-orang akan melupakan apa yang Anda lakukan, tetapi orang-orang tidak akan pernah melupakan bagaimana Anda membuat mereka merasa.", ref: "Maya Angelou" },
  { text: "Jika Anda tidak menyukai sesuatu, ubahlah. Jika Anda tidak bisa mengubahnya, ubahlah sikap Anda.", ref: "Maya Angelou" },
  { text: "Cobalah menjadi pelangi di awan orang lain.", ref: "Maya Angelou" },
  { text: "Kita mungkin menghadapi banyak kekalahan tetapi kita tidak boleh dikalahkan.", ref: "Maya Angelou" },
  { text: "Keberanian adalah kebajikan paling penting dari semua kebajikan karena tanpa keberanian, Anda tidak dapat mempraktikkan kebajikan lainnya secara konsisten.", ref: "Maya Angelou" },
  { text: "Saya telah belajar bahwa mencari nafkah tidak sama dengan membuat kehidupan.", ref: "Maya Angelou" },
  { text: "Cinta tidak mengenal hambatan. Ia melompati rintangan, melompati pagar, menembus dinding untuk tiba di tujuannya dengan penuh harapan.", ref: "Maya Angelou" },
  { text: "Tidak ada siksaan yang lebih besar daripada menyimpan cerita yang tak terungkap di dalam dirimu.", ref: "Maya Angelou" },
  { text: "Lakukan yang terbaik yang Anda bisa sampai Anda tahu lebih baik. Kemudian ketika Anda tahu lebih baik, lakukan lebih baik.", ref: "Maya Angelou" },
  { text: "Tujuan hidup kita adalah untuk menjadi bahagia.", ref: "Dalai Lama" },
  { text: "Kasih sayang dan toleransi bukanlah tanda-tanda kelemahan, melainkan tanda-tanda kekuatan.", ref: "Dalai Lama" },
  { text: "Ingatlah bahwa tidak mendapatkan apa yang Anda inginkan terkadang merupakan keberuntungan yang luar biasa.", ref: "Dalai Lama" },
  { text: "Aturan pertama: Jika Anda ingin orang lain bahagia, praktikkan kasih sayang. Aturan kedua: Jika Anda ingin bahagia, praktikkan kasih sayang.", ref: "Dalai Lama" },
  { text: "Rumah adalah tempat di mana Anda merasa damai.", ref: "Dalai Lama" },
  { text: "Bagilah pengetahuan Anda. Ini adalah cara untuk mencapai keabadian.", ref: "Dalai Lama" },
  { text: "Tindakan yang baik adalah ekspresi paling tulus dari jiwa kita.", ref: "Dalai Lama" },
  { text: "Sikap diam terkadang merupakan jawaban terbaik.", ref: "Dalai Lama" },
  { text: "Kalahkan kemarahan dengan cinta, kalahkan kejahatan dengan kebaikan.", ref: "Dalai Lama" },
  { text: "Hanya ada dua hari dalam setahun di mana tidak ada yang bisa dilakukan. Satu disebut kemarin dan yang lainnya disebut besok.", ref: "Dalai Lama" },
  { text: "Jadilah dirimu sendiri; orang lain sudah diambil.", ref: "Oscar Wilde" },
  { text: "Pengalaman hanyalah nama yang kita berikan untuk kesalahan kita.", ref: "Oscar Wilde" },
  { text: "Kekhawatiran adalah tanda bahwa seseorang memikirkan masa depan secara serius.", ref: "Oscar Wilde" },
  { text: "Cara terbaik untuk menghargai pekerjaan Anda adalah dengan membayangkan diri Anda tanpanya.", ref: "Oscar Wilde" },
  { text: "Buku yang disebut dunia moral atau amoral adalah buku yang ditulis dengan baik, atau ditulis dengan buruk. Itu saja.", ref: "Oscar Wilde" },
  { text: "Cinta diri adalah awal dari romansa seumur hidup.", ref: "Oscar Wilde" },
  { text: "Tidak ada orang yang cukup kaya untuk membeli kembali masa lalunya.", ref: "Oscar Wilde" },
  { text: "Rahasia hidup adalah menikmati kesenangan yang sangat sederhana.", ref: "Oscar Wilde" },
  { text: "Konsistensi adalah tempat berlindung terakhir bagi orang yang tidak imajinatif.", ref: "Oscar Wilde" },
  { text: "Tujuan hidup adalah pengembangan diri. Menyadari sifat seseorang dengan sempurna.", ref: "Oscar Wilde" },
  { text: "Percayalah Anda bisa dan Anda sudah setengah jalan.", ref: "Theodore Roosevelt" },
  { text: "Lakukan apa yang Anda bisa, dengan apa yang Anda miliki, di mana Anda berada.", ref: "Theodore Roosevelt" },
  { text: "Jauh lebih baik berani melakukan hal-hal hebat, memenangkan kemenangan gemilang, meskipun diwarnai kegagalan... daripada berbaris dengan roh-roh malang yang tidak menikmati atau menderita banyak.", ref: "Theodore Roosevelt" },
  { text: "Karakter, pada akhirnya, adalah faktor penentu dalam kehidupan seorang individu.", ref: "Theodore Roosevelt" },
  { text: "Satu-satunya orang yang tidak pernah membuat kesalahan adalah orang yang tidak pernah melakukan apa-apa.", ref: "Theodore Roosevelt" },
  { text: "Bicaralah dengan lembut dan bawalah tongkat besar; Anda akan melangkah jauh.", ref: "Theodore Roosevelt" },
  { text: "Tidak ada pencapaian berharga dalam hidup yang datang tanpa kerja keras dan pengorbanan.", ref: "Theodore Roosevelt" },
  { text: "Ketika Anda ditanya apakah Anda bisa melakukan pekerjaan, katakan padanya, \'Tentu saya bisa!\' Lalu mulailah mencari tahu bagaimana melakukannya.", ref: "Theodore Roosevelt" },
  { text: "Rasa hormat harus diperoleh, bukan diminta.", ref: "Theodore Roosevelt" },
  { text: "Pemimpin memimpin, bos menggerakkan.", ref: "Theodore Roosevelt" },
  { text: "Kosongkan pikiranmu, jadilah tanpa bentuk, tidak berbentuk, seperti air.", ref: "Bruce Lee" },
  { text: "Mengetahui saja tidak cukup, kita harus menerapkan. Kemauan saja tidak cukup, kita harus melakukan.", ref: "Bruce Lee" },
  { text: "Kunci keabadian adalah pertama-tama menjalani hidup yang layak diingat.", ref: "Bruce Lee" },
  { text: "Jangan berdoa untuk kehidupan yang mudah, berdoalah untuk kekuatan untuk menanggung kehidupan yang sulit.", ref: "Bruce Lee" },
  { text: "Kesalahan selalu dimaafkan, jika seseorang memiliki keberanian untuk mengakuinya.", ref: "Bruce Lee" },
  { text: "Jika Anda menghabiskan terlalu banyak waktu untuk memikirkan sesuatu, Anda tidak akan pernah menyelesaikannya.", ref: "Bruce Lee" },
  { text: "Pamer adalah ide orang bodoh tentang kemuliaan.", ref: "Bruce Lee" },
  { text: "Mengadopsi apa yang berguna, membuang apa yang tidak berguna, dan menambahkan apa yang khas milik Anda.", ref: "Bruce Lee" },
  { text: "Fokus adalah rahasia dari semua prajurit yang sukses.", ref: "Bruce Lee" },
  { text: "Seiring berjalannya waktu, air yang tenang akan menembus batu yang keras.", ref: "Bruce Lee" },
  { text: "Apa pun yang dapat dipahami dan diyakini oleh pikiran manusia, itu dapat dicapai.", ref: "Napoleon Hill" },
  { text: "Titik awal dari semua pencapaian adalah keinginan.", ref: "Napoleon Hill" },
  { text: "Kekuatan dan pertumbuhan datang hanya melalui upaya dan perjuangan yang terus-menerus.", ref: "Napoleon Hill" },
  { text: "Jangan menunggu. Waktunya tidak akan pernah \'tepat\'.", ref: "Napoleon Hill" },
  { text: "Setiap kesulitan, setiap kegagalan, setiap sakit hati membawa serta benih dari manfaat yang setara atau lebih besar.", ref: "Napoleon Hill" },
  { text: "Jika Anda tidak dapat melakukan hal-hal besar, lakukan hal-hal kecil dengan cara yang hebat.", ref: "Napoleon Hill" },
  { text: "Sukses tidak menuntut penjelasan. Kegagalan tidak mengizinkan alibi.", ref: "Napoleon Hill" },
  { text: "Pemenang tidak pernah menyerah dan orang yang menyerah tidak pernah menang.", ref: "Napoleon Hill" },
  { text: "Pikiran adalah satu-satunya kendali penuh yang diberikan alam kepada kita.", ref: "Napoleon Hill" },
  { text: "Rencana yang jelas adalah peta jalan Anda menuju kesuksesan.", ref: "Napoleon Hill" },
  { text: "Jangan membandingkan diri Anda dengan siapa pun di dunia ini... jika Anda melakukannya, Anda menghina diri sendiri.", ref: "Bill Gates" },
  { text: "Jika Anda lahir miskin, itu bukan kesalahan Anda, tetapi jika Anda mati miskin, itu adalah kesalahan Anda.", ref: "Bill Gates" },
  { text: "Peluang terbaik diperoleh dengan berinvestasi pada diri sendiri.", ref: "Bill Gates" },
  { text: "Pelanggan Anda yang paling tidak puas adalah sumber pembelajaran terbesar Anda.", ref: "Bill Gates" },
  { text: "Kita selalu melebih-lebihkan perubahan yang akan terjadi dalam dua tahun ke depan dan meremehkan perubahan yang akan terjadi dalam sepuluh tahun ke depan.", ref: "Bill Gates" },
  { text: "Sukses adalah guru yang buruk. Dia menggoda orang pintar untuk berpikir mereka tidak bisa kalah.", ref: "Bill Gates" },
  { text: "Untuk menang besar, terkadang Anda harus mengambil risiko besar.", ref: "Bill Gates" },
  { text: "Teknologi hanyalah alat. Dalam hal membuat anak-anak bekerja sama dan memotivasi mereka, guru adalah yang paling penting.", ref: "Bill Gates" },
  { text: "Optimisme adalah keyakinan yang mengarah pada pencapaian nyata.", ref: "Bill Gates" },
  { text: "Fokuslah pada misi Anda dan abaikan gangguan di sekitar Anda.", ref: "Bill Gates" },
  { text: "Hanya beli sesuatu yang Anda akan sangat senang menahannya jika pasar tutup selama sepuluh tahun.", ref: "Warren Buffett" },
  { text: "Dibutuhkan 20 tahun untuk membangun reputasi dan lima menit untuk merusaknya. Jika Anda memikirkan hal itu, Anda akan melakukan berbagai hal secara berbeda.", ref: "Warren Buffett" },
  { text: "Risiko datang dari ketidaktahuan tentang apa yang sedang Anda lakukan.", ref: "Warren Buffett" },
  { text: "Investasi terbaik yang dapat Anda lakukan adalah pada kemampuan Anda sendiri.", ref: "Warren Buffett" },
  { text: "Jauh lebih baik membeli perusahaan yang luar biasa dengan harga yang wajar daripada perusahaan yang wajar dengan harga yang luar biasa.", ref: "Warren Buffett" },
  { text: "Seseorang duduk di tempat teduh hari ini karena seseorang menanam pohon lama sekali.", ref: "Warren Buffett" },
  { text: "Perbedaan antara orang sukses dan orang yang sangat sukses adalah bahwa orang yang sangat sukses mengatakan tidak pada hampir semua hal.", ref: "Warren Buffett" },
  { text: "Kejujuran adalah hadiah yang sangat mahal. Jangan mengharapkannya dari orang murahan.", ref: "Warren Buffett" },
  { text: "Aturan Nomor 1: Jangan pernah kehilangan uang. Aturan Nomor 2: Jangan pernah melupakan Aturan Nomor 1.", ref: "Warren Buffett" },
  { text: "Pasar saham adalah alat untuk mentransfer uang dari orang yang tidak sabar ke orang yang sabar.", ref: "Warren Buffett" },
  { text: "Tantangan adalah hadiah yang memaksa kita mencari pusat gravitasi baru. Jangan melawannya. Temukan saja cara baru untuk berdiri.", ref: "Oprah Winfrey" },
  { text: "Semakin banyak Anda memuji dan merayakan hidup Anda, semakin banyak hal yang ada dalam hidup untuk dirayakan.", ref: "Oprah Winfrey" },
  { text: "Petualangan terbesar yang dapat Anda ambil adalah menjalani hidup impian Anda.", ref: "Oprah Winfrey" },
  { text: "Ubah luka Anda menjadi kebijaksanaan.", ref: "Oprah Winfrey" },
  { text: "Napas masuk, napas keluar, dan ingatkan dirimu bahwa momen inilah satu-satunya yang pasti kamu miliki.", ref: "Oprah Winfrey" },
  { text: "Saya yakin bahwa apa yang kita berikan ke dunia akan kembali kepada kita.", ref: "Oprah Winfrey" },
  { text: "Integritas adalah melakukan hal yang benar, mengetahui bahwa tidak ada yang akan tahu apakah Anda melakukannya atau tidak.", ref: "Oprah Winfrey" },
  { text: "Kelilingi dirimu hanya dengan orang-orang yang akan membawamu lebih tinggi.", ref: "Oprah Winfrey" },
  { text: "Anda menjadi apa yang Anda yakini. Anda berada di tempat Anda hari ini berdasarkan keyakinan itu.", ref: "Oprah Winfrey" },
  { text: "Kunci hidup bukanlah kesempurnaan, melainkan pertumbuhan yang berkelanjutan.", ref: "Oprah Winfrey" },
  { text: "Ketika ada sesuatu yang cukup penting, Anda melakukannya meskipun peluangnya tidak menguntungkan Anda.", ref: "Elon Musk" },
  { text: "Jika Anda bangun di pagi hari dan berpikir bahwa masa depan akan menjadi lebih baik, itu adalah hari yang cerah.", ref: "Elon Musk" },
  { text: "Kegagalan adalah pilihan di sini. Jika segala sesuatunya tidak gagal, Anda kurang berinovasi.", ref: "Elon Musk" },
  { text: "Ketekunan sangat penting. Anda tidak boleh menyerah kecuali Anda dipaksa untuk menyerah.", ref: "Elon Musk" },
  { text: "Sangat penting untuk menyukai orang-orang yang bekerja dengan Anda, jika tidak hidup Anda akan sengsara.", ref: "Elon Musk" },
  { text: "Saya pikir sangat mungkin bagi orang biasa untuk memilih menjadi luar biasa.", ref: "Elon Musk" },
  { text: "Fokuslah pada pembuatan produk atau layanan yang hebat.", ref: "Elon Musk" },
  { text: "Jika Anda ingin membuat sesuatu yang luar biasa, Anda harus sangat fokus pada detail terkecil.", ref: "Elon Musk" },
  { text: "Jangan ikuti tren. Fokuslah pada apa yang benar-benar penting bagi kehidupan manusia.", ref: "Elon Musk" },
  { text: "Kesalahan terbesar saya adalah terlalu mengandalkan bakat seseorang dan bukan kepribadiannya.", ref: "Elon Musk" },
  { text: "Kecantikan adalah tirani yang berumur pendek.", ref: "Socrates" },
  { text: "Orang bijak berbicara karena mereka memiliki sesuatu untuk dikatakan; orang bodoh karena mereka harus mengatakan sesuatu.", ref: "Socrates" },
  { text: "Jangan lakukan kepada orang lain apa yang membuat Anda marah jika dilakukan kepada Anda oleh orang lain.", ref: "Socrates" },
  { text: "Jujur adalah langkah pertama menuju kebijaksanaan.", ref: "Socrates" },
  { text: "Jiwa manusia tidak mati dan terus mencari kebenaran.", ref: "Socrates" },
  { text: "Harapan adalah mimpi dari mereka yang bangun.", ref: "Aristotle" },
  { text: "Pendidikan adalah hiasan dalam kemakmuran dan tempat perlindungan dalam kemalangan.", ref: "Aristotle" },
  { text: "Semua orang secara alami menginginkan pengetahuan.", ref: "Aristotle" },
  { text: "Mengetahui diri sendiri adalah awal dari semua kebenaran.", ref: "Aristotle" },
  { text: "Kebajikan adalah jalan tengah antara dua ekstrem.", ref: "Aristotle" },
  { text: "Keheningan adalah pelindung terbaik dari jiwa.", ref: "Confucius" },
  { text: "Keunggulan seseorang diukur dari tindakannya, bukan kata-katanya.", ref: "Confucius" },
  { text: "Kemarahan hanya akan merugikan diri Anda sendiri.", ref: "Confucius" },
  { text: "Pelajari masa lalu jika Anda ingin mendefinisikan masa depan.", ref: "Confucius" },
  { text: "Orang yang bertanya adalah orang bodoh selama lima menit, tetapi orang yang tidak bertanya tetap bodoh selamanya.", ref: "Confucius" },
  { text: "Bergaullah dengan orang-orang yang bisa mencerahkan pikiran Anda.", ref: "Seneca" },
  { text: "Hidup ini seperti drama: bukan panjangnya, melainkan keunggulan aktingnya yang penting.", ref: "Seneca" },
  { text: "Tidak ada yang lebih terhormat daripada hati yang penuh syukur.", ref: "Seneca" },
  { text: "Kita menderita karena pikiran kita sendiri.", ref: "Seneca" },
  { text: "Jangan biarkan hari ini berlalu tanpa peningkatan diri.", ref: "Seneca" },
  { text: "Segala sesuatu yang indah adalah indah karena dirinya sendiri.", ref: "Marcus Aurelius" },
  { text: "Batasi diri Anda pada masa kini.", ref: "Marcus Aurelius" },
  { text: "Lihat ke dalam diri Anda. Di dalam ada sumber kebaikan yang akan selalu melonjak jika Anda selalu menggali.", ref: "Marcus Aurelius" },
  { text: "Betapa ruginya orang yang tidak memperhatikan apa yang dilakukan tetangganya.", ref: "Marcus Aurelius" },
  { text: "Hidup adalah seni yang lebih mirip gulat daripada menari.", ref: "Marcus Aurelius" },
  { text: "Mengetahui orang lain adalah kecerdasan; mengetahui diri sendiri adalah kebijaksanaan sejati.", ref: "Lao Tzu" },
  { text: "Barangsiapa puas dengan apa yang dimilikinya adalah kaya.", ref: "Lao Tzu" },
  { text: "Ketika Anda puas menjadi diri sendiri dan tidak membandingkan atau bersaing, semua orang akan menghormati Anda.", ref: "Lao Tzu" },
  { text: "Dia yang tahu tidak berbicara. Dia yang berbicara tidak tahu.", ref: "Lao Tzu" },
  { text: "Jika Anda ingin memimpin orang, Anda harus berjalan di belakang mereka.", ref: "Lao Tzu" },
  { text: "Ingatlah bahwa Anda akan segera mati.", ref: "Steve Jobs" },
  { text: "Kerja keras adalah kunci dari kepuasan batin.", ref: "Steve Jobs" },
  { text: "Detail kecil membuat perbedaan besar.", ref: "Steve Jobs" },
  { text: "Fokus adalah kekuatan sejati.", ref: "Steve Jobs" },
  { text: "Kreativitas menghubungkan titik-titik masa lalu.", ref: "Steve Jobs" },
  { text: "Belajar dari kesalahan kemarin.", ref: "Albert Einstein" },
  { text: "Jangan pernah berhenti bertanya.", ref: "Albert Einstein" },
  { text: "Imajinasi melampaui batas pengetahuan.", ref: "Albert Einstein" },
  { text: "Sains tanpa etika adalah bahaya.", ref: "Albert Einstein" },
  { text: "Hidup adalah gerakan konstan.", ref: "Albert Einstein" },
  { text: "Saya sukses karena saya percaya.", ref: "Abraham Lincoln" },
  { text: "Karakter adalah fondasi utama.", ref: "Abraham Lincoln" },
  { text: "Jalan perlahan tapi pasti.", ref: "Abraham Lincoln" },
  { text: "Kebebasan adalah hak semua orang.", ref: "Abraham Lincoln" },
  { text: "Persatuan adalah kekuatan.", ref: "Abraham Lincoln" },
  { text: "Kerja keras mengalahkan bakat.", ref: "Thomas Edison" },
  { text: "Terus mencoba adalah kunci.", ref: "Thomas Edison" },
  { text: "Peluang sering kali berpakaian kerja keras.", ref: "Thomas Edison" },
  { text: "Gagal adalah bagian dari belajar.", ref: "Thomas Edison" },
  { text: "Ide tanpa eksekusi adalah sia-sia.", ref: "Thomas Edison" },
  { text: "Keberanian adalah berdiri.", ref: "Winston Churchill" },
  { text: "Optimisme adalah kekuatan.", ref: "Winston Churchill" },
  { text: "Sikap menentukan arah hidup.", ref: "Winston Churchill" },
  { text: "Kegagalan mengajarkan kita bertahan.", ref: "Winston Churchill" },
  { text: "Terus berjalan di masa sulit.", ref: "Winston Churchill" },
  { text: "Kedamaian dimulai dari diri sendiri.", ref: "Mahatma Gandhi" },
  { text: "Kesederhanaan adalah keindahan.", ref: "Mahatma Gandhi" },
  { text: "Kejujuran adalah integritas.", ref: "Mahatma Gandhi" },
  { text: "Pelayanan kepada sesama adalah kemuliaan.", ref: "Mahatma Gandhi" },
  { text: "Kekuatan moral mengalahkan fisik.", ref: "Mahatma Gandhi" },
  { text: "Semua tampak tidak mungkin sampai berhasil.", ref: "Nelson Mandela" },
  { text: "Pendidikan adalah senjata perubahan.", ref: "Nelson Mandela" },
  { text: "Keberanian mengalahkan ketakutan.", ref: "Nelson Mandela" },
  { text: "Masa depan milik anak-anak.", ref: "Nelson Mandela" },
  { text: "Hidup damai dengan sesama.", ref: "Nelson Mandela" },
  { text: "Jadilah seperti air.", ref: "Bruce Lee" },
  { text: "Mengetahui diri sendiri adalah kebebasan.", ref: "Bruce Lee" },
  { text: "Fokus pada satu hal.", ref: "Bruce Lee" },
  { text: "Ketekunan melatih kekuatan.", ref: "Bruce Lee" },
  { text: "Kesederhanaan dalam gerakan.", ref: "Bruce Lee" },
  { text: "Lakukan yang penting bagi Anda.", ref: "Elon Musk" },
  { text: "Gagal untuk berinovasi.", ref: "Elon Musk" },
  { text: "Fokus pada kualitas produk.", ref: "Elon Musk" },
  { text: "Jangan pernah menyerah.", ref: "Elon Musk" },
  { text: "Teknologi membantu manusia.", ref: "Elon Musk" },
  { text: "Belajar dari pelanggan Anda.", ref: "Bill Gates" },
  { text: "Investasi pada masa depan.", ref: "Bill Gates" },
  { text: "Inovasi membantu dunia.", ref: "Bill Gates" },
  { text: "Fokus pada tujuan Anda.", ref: "Bill Gates" },
  { text: "Pendidikan adalah kunci.", ref: "Bill Gates" },
  { text: "Sabar membawa kesuksesan.", ref: "Warren Buffett" },
  { text: "Reputasi sulit dibangun.", ref: "Warren Buffett" },
  { text: "Risiko datang dari ketidaktahuan.", ref: "Warren Buffett" },
  { text: "Investasi terbaik adalah diri sendiri.", ref: "Warren Buffett" },
  { text: "Kualitas di atas segalanya.", ref: "Warren Buffett" },
  { text: "Ubah luka jadi bijaksana.", ref: "Oprah Winfrey" },
  { text: "Syukuri apa yang Anda miliki.", ref: "Oprah Winfrey" },
  { text: "Petualangan terbesar adalah hidupmu.", ref: "Oprah Winfrey" },
  { text: "Integritas adalah melakukan yang benar.", ref: "Oprah Winfrey" },
  { text: "Kelilingi dirimu dengan kebaikan.", ref: "Oprah Winfrey" },
  { text: "Optimisme adalah keyakinan.", ref: "Helen Keller" },
  { text: "Bersama kita kuat.", ref: "Helen Keller" },
  { text: "Hadapi cahaya matahari.", ref: "Helen Keller" },
  { text: "Hidup adalah petualangan.", ref: "Helen Keller" },
  { text: "Karakter dibentuk dalam ujian.", ref: "Helen Keller" },
  { text: "Rahasia maju adalah memulai.", ref: "Mark Twain" },
  { text: "Kebaikan adalah bahasa universal.", ref: "Mark Twain" },
  { text: "Keberanian mengendalikan rasa takut.", ref: "Mark Twain" },
  { text: "Jujur adalah langkah awal.", ref: "Mark Twain" },
  { text: "Kebenaran mengalahkan fiksi.", ref: "Mark Twain" },
  { text: "Tindakan adalah kunci dasar untuk semua kesuksesan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Henry Ford", ref: "" },
  { text: "Masa depan Anda diciptakan oleh apa yang Anda lakukan hari ini, bukan besok. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Winston Churchill", ref: "" },
  { text: "Jangan biarkan kemarin mengambil terlalu banyak dari hari ini. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Mahatma Gandhi", ref: "" },
  { text: "Disiplin adalah jembatan antara tujuan dan pencapaian. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Nelson Mandela", ref: "" },
  { text: "Kunci kesuksesan adalah memusatkan pikiran sadar kita pada hal-hal yang kita inginkan, bukan hal-hal yang kita takuti. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Bruce Lee", ref: "" },
  { text: "Cara terbaik untuk memulai adalah berhenti berbicara dan mulai melakukan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Bill Gates", ref: "" },
  { text: "Semakin keras Anda bekerja untuk sesuatu, semakin besar perasaan Anda saat mencapainya. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Warren Buffett", ref: "" },
  { text: "Bermimpilah lebih besar. Lakukan lebih besar. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Oprah Winfrey", ref: "" },
  { text: "Jangan berhenti ketika Anda lelah. Berhentilah ketika Anda selesai. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Helen Keller", ref: "" },
  { text: "Bangun dengan tekad. Pergi tidur dengan kepuasan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Mark Twain", ref: "" },
  { text: "Lakukan sesuatu hari ini yang akan membuat diri Anda di masa depan berterima kasih. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Aristotle", ref: "" },
  { text: "Sedikit kemajuan setiap hari menghasilkan hasil yang besar. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Socrates", ref: "" },
  { text: "Ini akan sulit, tetapi sulit tidak berarti mustahil. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Confucius", ref: "" },
  { text: "Jangan menunggu kesempatan. Ciptakan kesempatan itu. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Seneca", ref: "" },
  { text: "Terkadang kita diuji bukan untuk menunjukkan kelemahan kita, tetapi untuk menemukan kekuatan kita. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Marcus Aurelius", ref: "" },
  { text: "Kunci sukses adalah fokus pada tujuan, bukan hambatan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Lao Tzu", ref: "" },
  { text: "Sukses bukanlah kunci kebahagiaan. Kebahagiaan adalah kunci kesuksesan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Steve Jobs", ref: "" },
  { text: "Yakinlah bahwa Anda bisa, dan Anda sudah setengah jalan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Albert Einstein", ref: "" },
  { text: "Jangan membatasi tantangan Anda. Tantang batas Anda. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Abraham Lincoln", ref: "" },
  { text: "Hanya Anda yang bisa mengubah hidup Anda. Tidak ada orang lain yang bisa melakukannya untuk Anda. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Thomas Edison", ref: "" },
  { text: "Tindakan adalah kunci dasar untuk semua kesuksesan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Henry Ford", ref: "" },
  { text: "Masa depan Anda diciptakan oleh apa yang Anda lakukan hari ini, bukan besok. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Winston Churchill", ref: "" },
  { text: "Jangan biarkan kemarin mengambil terlalu banyak dari hari ini. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Mahatma Gandhi", ref: "" },
  { text: "Disiplin adalah jembatan antara tujuan dan pencapaian. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Nelson Mandela", ref: "" },
  { text: "Kunci kesuksesan adalah memusatkan pikiran sadar kita pada hal-hal yang kita inginkan, bukan hal-hal yang kita takuti. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Bruce Lee", ref: "" },
  { text: "Cara terbaik untuk memulai adalah berhenti berbicara dan mulai melakukan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Bill Gates", ref: "" },
  { text: "Semakin keras Anda bekerja untuk sesuatu, semakin besar perasaan Anda saat mencapainya. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Warren Buffett", ref: "" },
  { text: "Bermimpilah lebih besar. Lakukan lebih besar. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Oprah Winfrey", ref: "" },
  { text: "Jangan berhenti ketika Anda lelah. Berhentilah ketika Anda selesai. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Helen Keller", ref: "" },
  { text: "Bangun dengan tekad. Pergi tidur dengan kepuasan. (Pelajaran hidup tentang kedisiplinan dan perjuangan) Mark Twain", ref: "" },
];


